text = "Artificial Intelligence"
print(len(text))
print(text[0:5])
print(text[-1])
print(text.lower())
print(text.replace("Intelligence", "Learning"))
print(text.split(" "))
print(text.upper())
print(text.find("Intelligence"))
print(text.isalpha())
print(text.count("i"))
print(text.startswith("Artificial"))
print(text.endswith("Learning"))
print(text[-1:-5:-1])
